name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install: |
              sudo apt-get update
              sudo apt-get install -y build-essential libsqlite3-dev libpcre3-dev zlib1g-dev libssl-dev perl wget curl nginx-dev
              sudo ln -s /usr/lib/x86_64-linux-gnu/libpcre.so /usr/lib/libpcre.so || true
          - os: macos-latest
            install: |
              brew install pcre openssl@1.1 sqlite3 wget curl
              brew install nginx
              # Force unlink and relink nginx to ensure headers are available
              brew unlink nginx || true
              brew link --force nginx
              # Verify nginx installation and headers
              nginx_prefix=$(brew --prefix nginx)
              echo "Nginx prefix: $nginx_prefix"
              ls -la $nginx_prefix/include || true
              ls -la $nginx_prefix/include/nginx || true
              # Export paths
              echo "NGINX_INC_PATH=$nginx_prefix/include/nginx" >> $GITHUB_ENV
              echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)" >> $GITHUB_ENV
              echo "PCRE_LIB_PATH=$(brew --prefix pcre)/lib/libpcre.dylib" >> $GITHUB_ENV
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: ${{ matrix.install }}
    
    - name: Build standalone module
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          make PCRE_LIB_PATH=/usr/lib/x86_64-linux-gnu/libpcre.so \
               STANDALONE=1 \
               all
        else
          echo "Debug: Environment variables:"
          echo "NGINX_INC_PATH=$NGINX_INC_PATH"
          echo "OPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR"
          echo "PCRE_LIB_PATH=$PCRE_LIB_PATH"
          make PCRE_LIB_PATH="$PCRE_LIB_PATH" \
               OPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" \
               NGINX_INC_PATH="$NGINX_INC_PATH" \
               STANDALONE=1 \
               all
        fi
    
    - name: Basic module verification
      run: |
        echo "Verifying module was built..."
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          test -f standalone/objs/ngx_http_robonope_module.so || exit 1
          file standalone/objs/ngx_http_robonope_module.so | grep -q 'shared object' || exit 1
        else
          test -f standalone/objs/ngx_http_robonope_module.so || exit 1
          file standalone/objs/ngx_http_robonope_module.so | grep -q 'dynamically linked shared library' || exit 1
        fi
        echo "Module verification successful"
    
    - name: Create release package
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      run: make STANDALONE=1 release
    
    - name: Upload release artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: robonope-module
        path: robonope-module-*.tar.gz
        retention-days: 7 