name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install: |
              sudo apt-get update
              sudo apt-get install -y build-essential libsqlite3-dev libpcre3-dev zlib1g-dev libssl-dev perl wget curl
              sudo ln -s /usr/lib/x86_64-linux-gnu/libpcre.so /usr/lib/libpcre.so || true
          - os: macos-latest
            install: |
              brew install pcre openssl@1.1 sqlite3 wget curl
              OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
              echo "PCRE_LIB_PATH=$(brew --prefix pcre)/lib/libpcre.dylib" >> $GITHUB_ENV
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: ${{ matrix.install }}
    
    - name: Prepare build environment
      run: |
        rm -rf build
        mkdir -p build
        cd build
        wget -q https://nginx.org/download/nginx-1.24.0.tar.gz
        tar xzf nginx-1.24.0.tar.gz
        wget -q https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download -O pcre-8.45.tar.gz
        tar xzf pcre-8.45.tar.gz
        wget -q https://www.openssl.org/source/openssl-1.1.1w.tar.gz
        tar xzf openssl-1.1.1w.tar.gz
        rm -f *.tar.gz
        cd pcre-8.45
        ./configure --enable-static --disable-shared
        make
        cd ..
        # Create a flag file to indicate dependencies are ready
        touch .deps-ready
    
    - name: Build module
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          make PCRE_LIB_PATH=/usr/lib/x86_64-linux-gnu/libpcre.so \
               SKIP_DEPS=1 \
               all
        else
          make PCRE_LIB_PATH=$(brew --prefix pcre)/lib/libpcre.dylib \
               SKIP_DEPS=1 \
               all
        fi
    
    - name: Run tests
      run: make test
    
    - name: Create release package
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      run: make release
    
    - name: Upload release artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: robonope-module
        path: robonope-module-*.tar.gz
        retention-days: 7

  standalone:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev libpcre3-dev zlib1g-dev libssl-dev perl wget curl nginx-dev
        sudo ln -s /usr/lib/x86_64-linux-gnu/libpcre.so /usr/lib/libpcre.so || true
    
    - name: Prepare build environment
      run: |
        rm -rf build
        mkdir -p build
        cd build
        wget -q https://nginx.org/download/nginx-1.24.0.tar.gz
        tar xzf nginx-1.24.0.tar.gz
        wget -q https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download -O pcre-8.45.tar.gz
        tar xzf pcre-8.45.tar.gz
        wget -q https://www.openssl.org/source/openssl-1.1.1w.tar.gz
        tar xzf openssl-1.1.1w.tar.gz
        rm -f *.tar.gz
        cd pcre-8.45
        ./configure --enable-static --disable-shared
        make
        cd ..
        # Create a flag file to indicate dependencies are ready
        touch .deps-ready
    
    - name: Build standalone module
      run: |
        make PCRE_LIB_PATH=/usr/lib/x86_64-linux-gnu/libpcre.so \
             SKIP_DEPS=1 \
             STANDALONE=1
    
    - name: Create standalone package
      run: make STANDALONE=1 install
    
    - name: Upload standalone artifact
      uses: actions/upload-artifact@v4
      with:
        name: robonope-standalone
        path: standalone/
        retention-days: 7 